FROM node:20.18

# ARG ENDPOINT_TRACK
# ARG ENDPOINT_PLAYLIST
# ARG ENDPOINT_UPDATE
# ARG NEXT_PUBLIC_API_TRACK
# ARG NEXT_PUBLIC_API_PLAYLIST
# ARG NEXT_PUBLIC_API_UPDATE

# ENV ENDPOINT_TRACK=${ENDPOINT_TRACK}
# ENV ENDPOINT_PLAYLIST=${ENDPOINT_PLAYLIST}
# ENV ENDPOINT_UPDATE=${ENDPOINT_UPDATE}
# ENV NEXT_PUBLIC_API_TRACK=${NEXT_PUBLIC_API_TRACK}
# ENV NEXT_PUBLIC_API_PLAYLIST=${NEXT_PUBLIC_API_PLAYLIST}
# ENV NEXT_PUBLIC_API_UPDATE=${NEXT_PUBLIC_API_UPDATE}

RUN apt-get update && apt-get install -y iputils-ping

WORKDIR /app

COPY package*.json .

RUN npm install 

COPY . .

CMD ["npm", "run", "dev"]