import 'dotenv/config'

export const {
    API_URL, 
    API_ENDPOINT_TRACK, 
    API_ENDPOINT_PLAYLIST, 
    API_ENDPOINT_UPDATE,
    NEXT_PUBLIC_API_TRACK,
    NEXT_PUBLIC_API_PLAYLIST,
    NEXT_PUBLIC_API_UPDATE
} = process.env
