const PLAYER_BORDER_VALUE = 28
const PLAYER_BORDER_VALUE_2 = PLAYER_BORDER_VALUE + 2
const DEFAULT_COLOR = '#555555'
const DEFAULT_COLOR_2 = '#ffffff'
const BRIGHTNESS_THRESHOLD_WHITE = 240
const BRIGHTNESS_THRESHOLD_BLACK = 100
const MOBILE_THUMB_WIDHT = '75%'
const DROP_SHADOW_WRAP_ALPHA = 'cc'
const DROP_SHADOW_WRAP_BLUR = '20px'
const LIST_ITEM_BG_ALPHA = '22'

export {PLAYER_BORDER_VALUE, DEFAULT_COLOR, DEFAULT_COLOR_2, BRIGHTNESS_THRESHOLD_WHITE, BRIGHTNESS_THRESHOLD_BLACK, MOBILE_THUMB_WIDHT, DROP_SHADOW_WRAP_ALPHA, DROP_SHADOW_WRAP_BLUR, PLAYER_BORDER_VALUE_2, LIST_ITEM_BG_ALPHA}